import {
  SystemIcon,
  SquaresIcon,
  BuildingIcon,
  CodeIcon,
  KlubStackIcon,
  FlyingFoxLabsIcon,
  SkyteXIcon,
  ReactIcon,
  NextJSIcon,
  TypeScriptIcon,
  JavaScriptIcon,
  ReduxIcon,
  TailwindCSSIcon,
  NodeJSIcon,
  MongoDBIcon,
  PgSQLIcon,
  RedisIcon,
  DockerIcon,
  ViteIcon,
  NestJSIcon,
  HTMLIcon,
  CSSIcon,
  LinuxIcon,
  BootStrapIcon,
  ExpressIcon,
  TrendsetBanner,
  MentrosClubBanner,
  ChatAppBanner,
} from "@/assets/images";

export const serviceData = [
  {
    id: 1,
    icon: SquaresIcon,
    title: "UI & UX",
    desc: "Crafting intuitive, user-friendly interfaces.",
  },
  {
    id: 2,
    icon: SystemIcon,
    title: "Web & Mobile",
    desc: "Building responsive apps for all devices.",
  },
  {
    id: 3,
    icon: BuildingIcon,
    title: "Design & Creative",
    desc: "Creating visually stunning designs.",
  },
  {
    id: 4,
    icon: CodeIcon,
    title: "Development",
    desc: "Developing robust, scalable solutions.",
  },
];

export const educationData = [
  {
    id: "1",
    institute: "KKR & KSR Institute of Technology and Sciences",
    degree: "B.Tech in Electrical and Electronics Engineering",
    duration: "2019 – 2023",
    location: "Guntur, Andhra Pradesh",
    gpa: "7.01",
  },
  {
    id: "2",
    institute: "Sri Gayatri Junior College",
    degree: "PMC [Intermediate]",
    duration: "2017 – 2019",
    location: "Guntur, Andhra Pradesh",
    gpa: "7.33",
  },
  {
    id: "3",
    institute: "Naveena High School",
    degree: "Higher Secondary ( X )",
    duration: "2016 – 2017",
    location: "Guntur, Andhra Pradesh",
    gpa: "9.2",
  },
];

export const workExperienceData = [
  {
    id: "1",
    logo: SkyteXIcon,
    company: "Skytex Unmanned Aerial Solutions",
    role: "Software Developer Engineer 1",
    location: "Bengaluru, Karnataka",
    duration: "Mar 2025 - Present",
    responsibilities: [
      "Designed Offline Map System with OSM & Google Maps tile caching, improving large-area load speed by 25%.",
      "Built real-time AMSL graph for drone telemetry with automated terrain-collision detection, enhancing flight safety.",
      "Developed Drone Parameter CRUD APIs with Redis caching, reducing response times by 50%.",
    ],
    technologies: [
      "React.js",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "Redis",
      "Redux",
      "PostgreSQL",
      "Docker",
    ],
  },
  {
    id: "2",
    logo: FlyingFoxLabsIcon,
    company: "FlyingFox Labs Pvt Ltd",
    role: "Software Developer",
    location: "Hyderabad, Telangana",
    duration: "Feb 2024 - Feb 2025",
    responsibilities: [
      "Customized Keycloak themes & SSO integration, cutting onboarding time by 30%.",
      "Built Meeting Scheduling App with real-time availability, reducing the booking time by 30%.",
      "Developed a real-time multiplayer game with Socket.io, boosting interactivity & engagement.",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Zustand",
      "Tamagui",
      "Node.js",
      "Nest.js",
      "MongoDB",
      "Docker",
    ],
  },
  {
    id: "3",
    logo: KlubStackIcon,
    company: "KLUBSTACK",
    role: "Frontend Developer",
    location: "Chennai, TamilNadu",
    duration: "Jun 2023 - Jan 2024",
    responsibilities: [
      "Built Email Automation App using Next.js, improving interactivity by 25%.",
      "Migrated large codebase to Next.js + TypeScript, increasing maintainability by 30%.",
      "Optimized performance with 15% faster page load times.",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "Redux",
      "MaterislUI",
      "shadcn/ui",
      "TailwindCSS",
      "Node.js",
      "Nest.js",
      "MongoDB",
    ],
  },
];

export const navigators = [
  { name: "About", id: "about" },
  { name: "Skills", id: "skills" },
  { name: "Experience/Education", id: "experience" },
  { name: "Projects", id: "projects" },
  { name: "Services", id: "services" },
  { name: "Connect Me", id: "connect" },
];

export const skillItems = [
  { name: "React", icon: ReactIcon },
  { name: "Next.js", icon: NextJSIcon },
  { name: "TypeScript", icon: TypeScriptIcon },
  { name: "JavaScript", icon: JavaScriptIcon },
  { name: "Redux", icon: ReduxIcon },
  { name: "Tailwind CSS", icon: TailwindCSSIcon },
  { name: "Node.js", icon: NodeJSIcon },
  { name: "MongoDB", icon: MongoDBIcon },
  { name: "PostgreSQL", icon: PgSQLIcon },
  { name: "Redis", icon: RedisIcon },
  { name: "Docker", icon: DockerIcon },
  { name: "Vite", icon: ViteIcon },
  { name: "NestJS", icon: NestJSIcon },
  { name: "HTML5", icon: HTMLIcon },
  { name: "CSS3", icon: CSSIcon },
  { name: "Linux", icon: LinuxIcon },
  { name: "BootStrap", icon: BootStrapIcon },
  { name: "Express.js", icon: ExpressIcon },
];

export const projects = [
  {
    id: 1,
    image: TrendsetBanner,
    title: "Trendset E-commerce Web App",
    live_link: "https://trendsetnext.vercel.app/",
    github_link: "https://github.com/RajuNiranjan/ecommerce_next_frontend",
    tech_stack: [
      "Next.js",
      "JavaScript",
      "Redux",
      "TailwindCSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Cloudinary",
    ],
    desc: [
      "Developed a full-featured clothing e-commerce platform with Next.js and TailwindCSS.",
      "Integrated secure user and seller authentication using JWT.",
      "Implemented cart, wishlist, and order tracking using Redux Toolkit.",
      "Enabled product image uploads with Cloudinary for scalability.",
      "Built dynamic and reusable UI components with shadcn/ui.",
    ],
  },
  {
    id: 2,
    image: MentrosClubBanner,
    title: "MentorsKlub Meeting Web App",
    live_link: "https://mentorsklub.vercel.app/",
    github_link: "https://github.com/Abhisek0721/mentorsklub-frontend",
    tech_stack: [
      "React.js",
      "JavaScript",
      "Redux",
      "TailwindCSS",
      "Nest.js",
      "MongoDB",
      "Node.js",
    ],
    desc: [
      "Built a platform for scheduling and conducting mentorship meetings.",
      "Implemented secure user authentication and role-based access control.",
      "Enabled booking and calendar management for mentors and mentees.",
      "Used Redux for state management across the app.",
      "Designed responsive and modern UI using TailwindCSS.",
    ],
  },
  {
    id: 3,
    image: ChatAppBanner,
    title: "Real-time Chat Web App",
    live_link: "https://chat-app-phi-taupe.vercel.app/",
    github_link: "https://github.com/RajuNiranjan/chat-app",
    tech_stack: [
      "React.js",
      "TypeScript",
      "Zustand",
      "TailwindCSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.io",
    ],
    desc: [
      "Developed a real-time chat application using Socket.io and React.",
      "Used Zustand for efficient and lightweight state management.",
      "Implemented one-on-one messaging with real-time updates.",
      "Created chat room functionalities with persistent message history.",
      "Used TypeScript for type safety and maintainability.",
    ],
  },
];
